[package]
name = "evml"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chumsky = "0.11.1"
revm = "30.2.0"
smallvec = "1.15.1"

[[bin]]
name = "evml"
test = false

[lints.clippy]
complexity = "allow"
new_without_default = "allow"
unnecessary_lazy_evaluations = "allow"

[dev-dependencies]
insta = { version = "1.47.2", features = ["yaml"] }
